// ============================================================
// Notifications Agent — مهندس الإشعارات
// يعد Push Notifications و FCM والمعالجة في الخلفية
// ============================================================

import { CodeFile } from '../runtime/types';
import { SharedContext } from '../runtime/shared-context';
import { addLog, generateLogId } from '../runtime/memory';

export async function runNotificationsAgent(ctx: SharedContext): Promise<void> {
  const projectId = ctx.projectId;

  addLog(projectId, {
    id: generateLogId(),
    projectId,
    agent: 'notifications',
    action: 'start_setup',
    content: 'بدأ إعداد نظام الإشعارات...',
    status: 'running',
    timestamp: new Date().toISOString(),
  });

  try {
    // Generate Firebase config
    ctx.addCodeFile({
      path: 'src/lib/firebase.ts',
      content: generateFirebaseConfig(),
      language: 'typescript',
    });

    // Generate notification service worker
    ctx.addCodeFile({
      path: 'public/firebase-messaging-sw.js',
      content: generateServiceWorker(),
      language: 'javascript',
    });

    // Generate notification hooks
    ctx.addCodeFile({
      path: 'src/hooks/use-notifications.ts',
      content: generateNotificationHook(),
      language: 'typescript',
    });

    // Generate notification API route
    ctx.addCodeFile({
      path: 'src/app/api/notifications/route.ts',
      content: generateNotificationApi(),
      language: 'typescript',
    });

    // Generate notification component
    ctx.addCodeFile({
      path: 'src/components/NotificationProvider.tsx',
      content: generateNotificationProvider(),
      language: 'typescript',
    });

    ctx.setAgentResult('notifications', {
      type: 'Firebase Cloud Messaging',
      features: ['Push Notifications', 'Background Handler', 'Token Management', 'Notification Provider'],
      status: 'completed',
    });

    ctx.addMessage('notifications', 'frontend', 'تم إعداد نظام الإشعارات — استخدم useNotification hook', 'result');
    ctx.addMessage('notifications', 'qa_debug', 'نظام الإشعارات جاهز للفحص', 'result');

    addLog(projectId, {
      id: generateLogId(),
      projectId,
      agent: 'notifications',
      action: 'setup_complete',
      content: 'تم إعداد نظام الإشعارات مع Firebase Cloud Messaging',
      status: 'success',
      timestamp: new Date().toISOString(),
    });

    ctx.setProgress(72);
  } catch (error) {
    const errMsg = error instanceof Error ? error.message : 'خطأ في إعداد الإشعارات';
    ctx.addMessage('notifications', 'all', `فشل إعداد الإشعارات: ${errMsg}`, 'error');
    addLog(projectId, {
      id: generateLogId(),
      projectId,
      agent: 'notifications',
      action: 'setup_error',
      content: errMsg,
      status: 'error',
      timestamp: new Date().toISOString(),
    });
    throw error;
  }
}

function generateFirebaseConfig(): string {
  return `// Firebase Configuration — Generated by Notifications Agent
import { initializeApp, getApps } from 'firebase/app';
import { getMessaging, isSupported } from 'firebase/messaging';

const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

// Initialize Firebase (prevent re-initialization)
const app = getApps().length === 0 ? initializeApp(firebaseConfig) : getApps()[0];

// Initialize Cloud Messaging
let messaging: ReturnType<typeof getMessaging> | null = null;

export async function getFirebaseMessaging() {
  if (messaging) return messaging;
  const supported = await isSupported();
  if (supported) {
    messaging = getMessaging(app);
  }
  return messaging;
}

export { app };
`;
}

function generateServiceWorker(): string {
  return `// Firebase Messaging Service Worker — Generated by Notifications Agent
importScripts('https://www.gstatic.com/firebasejs/10.7.1/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.7.1/firebase-messaging-compat.js');

firebase.initializeApp({
  apiKey: '',
  authDomain: '',
  projectId: '',
  storageBucket: '',
  messagingSenderId: '',
  appId: '',
});

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  const title = payload.notification?.title || 'إشعار جديد';
  const options = {
    body: payload.notification?.body || '',
    icon: '/icon-192x192.png',
    badge: '/badge-72x72.png',
    dir: 'rtl' as const,
    lang: 'ar',
  };
  
  self.registration.showNotification(title, options);
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  event.waitUntil(
    self.clients.openWindow('/')
  );
});
`;
}

function generateNotificationHook(): string {
  return `'use client';

import { useState, useEffect, useCallback } from 'react';
import { getFirebaseMessaging } from '@/lib/firebase';
import { getToken, onMessage, deleteToken } from 'firebase/messaging';

export function useNotifications() {
  const [token, setToken] = useState<string | null>(null);
  const [permission, setPermission] = useState<NotificationPermission>('default');
  const [messages, setMessages] = useState<unknown[]>([]);

  const requestPermission = useCallback(async () => {
    try {
      const result = await Notification.requestPermission();
      setPermission(result);
      
      if (result === 'granted') {
        const messaging = await getFirebaseMessaging();
        if (messaging) {
          const currentToken = await getToken(messaging, {
            vapidKey: process.env.NEXT_PUBLIC_FIREBASE_VAPID_KEY,
          });
          setToken(currentToken);
        }
      }
    } catch (error) {
      console.error('فشل في طلب إذن الإشعارات:', error);
    }
  }, []);

  const revokePermission = useCallback(async () => {
    try {
      const messaging = await getFirebaseMessaging();
      if (messaging && token) {
        await deleteToken(messaging);
        setToken(null);
        setPermission('default');
      }
    } catch (error) {
      console.error('فشل في إلغاء الإشعارات:', error);
    }
  }, [token]);

  useEffect(() => {
    const setupListener = async () => {
      const messaging = await getFirebaseMessaging();
      if (messaging) {
        onMessage(messaging, (payload) => {
          setMessages(prev => [...prev, payload]);
        });
      }
    };
    
    setupListener();
  }, []);

  return {
    token,
    permission,
    messages,
    requestPermission,
    revokePermission,
  };
}
`;
}

function generateNotificationApi(): string {
  return `import { NextRequest, NextResponse } from 'next/server';

// Send notification via FCM — Generated by Notifications Agent
export async function POST(request: NextRequest) {
  try {
    const { token, title, body, data } = await request.json();

    if (!token || !title || !body) {
      return NextResponse.json(
        { error: 'token, title, body مطلوبة' },
        { status: 400 }
      );
    }

    // Use Firebase Admin SDK to send notification
    // For now, return success (implement server-side FCM sending)
    console.log('Sending notification:', { token, title, body, data });

    return NextResponse.json({
      success: true,
      message: 'تم إرسال الإشعار بنجاح',
    });
  } catch (error) {
    return NextResponse.json(
      { error: 'فشل في إرسال الإشعار' },
      { status: 500 }
    );
  }
}
`;
}

function generateNotificationProvider(): string {
  return `'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { getFirebaseMessaging } from '@/lib/firebase';
import { onMessage } from 'firebase/messaging';

interface Notification {
  id: string;
  title: string;
  body: string;
  timestamp: Date;
  read: boolean;
}

interface NotificationContextType {
  notifications: Notification[];
  unreadCount: number;
  markAsRead: (id: string) => void;
  markAllAsRead: () => void;
}

const NotificationContext = createContext<NotificationContextType>({
  notifications: [],
  unreadCount: 0,
  markAsRead: () => {},
  markAllAsRead: () => {},
});

export function NotificationProvider({ children }: { children: ReactNode }) {
  const [notifications, setNotifications] = useState<Notification[]>([]);

  useEffect(() => {
    const setup = async () => {
      const messaging = await getFirebaseMessaging();
      if (messaging) {
        onMessage(messaging, (payload) => {
          const notification: Notification = {
            id: Date.now().toString(),
            title: payload.notification?.title ?? 'إشعار جديد',
            body: payload.notification?.body ?? '',
            timestamp: new Date(),
            read: false,
          };
          setNotifications(prev => [notification, ...prev]);
        });
      }
    };
    setup();
  }, []);

  const markAsRead = (id: string) => {
    setNotifications(prev =>
      prev.map(n => (n.id === id ? { ...n, read: true } : n))
    );
  };

  const markAllAsRead = () => {
    setNotifications(prev => prev.map(n => ({ ...n, read: true })));
  };

  const unreadCount = notifications.filter(n => !n.read).length;

  return (
    <NotificationContext.Provider value={{ notifications, unreadCount, markAsRead, markAllAsRead }}>
      {children}
    </NotificationContext.Provider>
  );
}

export function useNotificationContext() {
  return useContext(NotificationContext);
}
`;
}
