// ============================================================
// UI/UX Agent — يصمم الواجهات ويحسن تجربة المستخدم بإبداع
// ============================================================

import { CodeFile } from '../runtime/types';
import { SharedContext } from '../runtime/shared-context';
import { addLog, generateLogId } from '../runtime/memory';

export async function runUiUxAgent(ctx: SharedContext): Promise<void> {
  const projectId = ctx.projectId;

  addLog(projectId, {
    id: generateLogId(),
    projectId,
    agent: 'ui_ux',
    action: 'start_design',
    content: 'بدأ تصميم نظام الواجهات وتجربة المستخدم...',
    status: 'running',
    timestamp: new Date().toISOString(),
  });

  try {
    // Generate design system
    const designSystem = generateDesignSystem(ctx.idea);

    // Generate color palette file
    ctx.addCodeFile({
      path: 'src/styles/design-system.ts',
      content: designSystem.code,
      language: 'typescript',
    });

    // Generate tailwind config
    ctx.addCodeFile({
      path: 'tailwind.config.ts',
      content: generateTailwindConfig(designSystem.colors),
      language: 'typescript',
    });

    // Generate component specifications
    ctx.addCodeFile({
      path: 'docs/ui-specs.md',
      content: generateUiSpecs(ctx, designSystem),
      language: 'markdown',
    });

    ctx.setAgentResult('ui_ux', {
      designSystem,
      colors: designSystem.colors,
      typography: designSystem.typography,
      spacing: designSystem.spacing,
    });

    ctx.addMessage('ui_ux', 'frontend', 'تم تصميم نظام الواجهات — استخدم الألوان والمكونات المحددة', 'result');

    addLog(projectId, {
      id: generateLogId(),
      projectId,
      agent: 'ui_ux',
      action: 'design_complete',
      content: `تم التصميم: ${designSystem.colors.primary} | خطوط: ${designSystem.typography.heading}`,
      status: 'success',
      timestamp: new Date().toISOString(),
    });

    ctx.setProgress(25);
  } catch (error) {
    const errMsg = error instanceof Error ? error.message : 'خطأ في التصميم';
    ctx.addMessage('ui_ux', 'all', `فشل التصميم: ${errMsg}`, 'error');
    addLog(projectId, {
      id: generateLogId(),
      projectId,
      agent: 'ui_ux',
      action: 'design_error',
      content: errMsg,
      status: 'error',
      timestamp: new Date().toISOString(),
    });
    throw error;
  }
}

interface DesignSystem {
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    foreground: string;
    muted: string;
    destructive: string;
  };
  typography: {
    heading: string;
    body: string;
    mono: string;
  };
  spacing: string;
  borderRadius: string;
  code: string;
}

function generateDesignSystem(idea: string): DesignSystem {
  // Generate color palette based on idea theme
  const isEcommerce = /متجر|shop|ecommerce|بيع|تسوق/i.test(idea);
  const isSocial = /اجتماع|social|chat|محادثة|تواصل/i.test(idea);
  const isEducation = /تعلم|education|course|دورة|درس/i.test(idea);
  const isHealth = /صح|health|طب|doctor|عيادة/i.test(idea);

  let colors: DesignSystem['colors'];
  if (isEcommerce) {
    colors = { primary: '#059669', secondary: '#0891b2', accent: '#d97706', background: '#ffffff', foreground: '#111827', muted: '#6b7280', destructive: '#dc2626' };
  } else if (isSocial) {
    colors = { primary: '#7c3aed', secondary: '#ec4899', accent: '#06b6d4', background: '#ffffff', foreground: '#111827', muted: '#6b7280', destructive: '#dc2626' };
  } else if (isEducation) {
    colors = { primary: '#2563eb', secondary: '#059669', accent: '#f59e0b', background: '#ffffff', foreground: '#111827', muted: '#6b7280', destructive: '#dc2626' };
  } else if (isHealth) {
    colors = { primary: '#0d9488', secondary: '#2563eb', accent: '#10b981', background: '#ffffff', foreground: '#111827', muted: '#6b7280', destructive: '#dc2626' };
  } else {
    colors = { primary: '#7c3aed', secondary: '#06b6d4', accent: '#f59e0b', background: '#ffffff', foreground: '#111827', muted: '#6b7280', destructive: '#dc2626' };
  }

  return {
    colors,
    typography: {
      heading: 'Inter / Cairo',
      body: 'Inter / Cairo',
      mono: 'JetBrains Mono',
    },
    spacing: '4px base unit',
    borderRadius: '8px / 12px',
    code: `// Design System — Auto-generated by UI/UX Agent
export const colors = ${JSON.stringify(colors, null, 2)};

export const typography = {
  heading: { fontFamily: 'Inter, Cairo, sans-serif', fontWeight: '700' },
  body: { fontFamily: 'Inter, Cairo, sans-serif', fontWeight: '400' },
  mono: { fontFamily: 'JetBrains Mono, monospace' },
};

export const spacing = { unit: 4, sm: 8, md: 16, lg: 24, xl: 32, '2xl': 48 };
export const borderRadius = { sm: 6, md: 8, lg: 12, xl: 16, full: 9999 };
`,
  };
}

function generateTailwindConfig(colors: DesignSystem['colors']): string {
  return `import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        primary: "${colors.primary}",
        secondary: "${colors.secondary}",
        accent: "${colors.accent}",
        background: "${colors.background}",
        foreground: "${colors.foreground}",
        muted: "${colors.muted}",
        destructive: "${colors.destructive}",
      },
      fontFamily: {
        heading: ["Inter", "Cairo", "sans-serif"],
        body: ["Inter", "Cairo", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};

export default config;
`;
}

function generateUiSpecs(ctx: SharedContext, design: DesignSystem): string {
  const pages = ctx.executionPlan?.steps.find(s => s.agent === 'project_manager')?.task ?? 'الصفحات';

  return `# مواصفات واجهة المستخدم

## نظام الألوان
- الأساسي: ${design.colors.primary}
- الثانوي: ${design.colors.secondary}
- التمييز: ${design.colors.accent}
- الخلفية: ${design.colors.background}
- النص: ${design.colors.foreground}

## الخطوط
- العناوين: ${design.typography.heading}
- النص: ${design.typography.body}
- الكود: ${design.typography.mono}

## المكونات المطلوبة
- Header / Navbar مع قائمة تنقل
- Footer ثابت
- بطاقات المحتوى
- نماذج الإدخال
- أزرار CTA
- نظام Toast للإشعارات
- جداول البيانات (إن لزم)

## الصفحات
${pages}

## مبادئ التصميم
1. تصميم متجاوب (Mobile-First)
2. دعم RTL للعربية
3. ألوان متوازنة ومريحة
4. مسافات متناسقة
5. انتقالات سلسة
`;
}
